FROM nginx@sha256:babad783dca44e555a1d3892a462bc798b2eb3ac462be93da8bea9db344f8bbc

COPY nginx.conf /etc/nginx/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown nginx:root /etc/nginx/nginx.conf
RUN chmod 440 /etc/nginx/nginx.conf
RUN chmod +x /custom-entrypoint.sh
RUN apt-get update && apt-get install -y procps

ENTRYPOINT ["/custom-entrypoint.sh"]
