FROM nginx:latest

COPY nginx.conf /etc/nginx/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown nginx:root /etc/nginx/nginx.conf
RUN chmod 440 /etc/nginx/nginx.conf
RUN chmod +x /custom-entrypoint.sh
RUN apt-get update && apt-get install -y procps

ENTRYPOINT ["/custom-entrypoint.sh"]
