FROM nginx@sha256:5ed8fcc66f4ed123c1b2560ed708dc148755b6e4cbd8b943fab094f2c6bfa91e

COPY nginx.conf /etc/nginx/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown nginx:root /etc/nginx/nginx.conf
RUN chmod 440 /etc/nginx/nginx.conf
RUN chmod +x /custom-entrypoint.sh
RUN apt-get update && apt-get install -y procps

ENTRYPOINT ["/custom-entrypoint.sh"]
