FROM python@sha256:416855cb95a0dd2b7149c91f4af88549def1af9c6c4fa9ab78404578bc97271d

WORKDIR /app
COPY docker-entrypoint.sh /app/docker-entrypoint.sh
COPY requirements.txt /app/requirements.txt
COPY scheduler.py /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt
RUN chmod +x /app/docker-entrypoint.sh /app/scheduler.py
RUN apt update && apt install -y procps

ENTRYPOINT ["/app/docker-entrypoint.sh"]
