FROM rabbitmq:4

RUN groupmod -g 3001 rabbitmq && usermod -u 3001 rabbitmq -g 3001
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown -R rabbitmq:root /etc/rabbitmq
RUN chmod 440 /etc/rabbitmq/rabbitmq.conf
RUN chmod +x /custom-entrypoint.sh
RUN rabbitmq-plugins enable rabbitmq_management rabbitmq_prometheus

ENTRYPOINT ["/custom-entrypoint.sh"]
