FROM rabbitmq@sha256:42ecb6d18fbd64ce9c0e4067f7b7f7015c1f73b7dac7f8aeaca588e2a22c1817

RUN groupmod -g 3001 rabbitmq && usermod -u 3001 rabbitmq -g 3001
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown -R rabbitmq:root /etc/rabbitmq
RUN chmod 440 /etc/rabbitmq/rabbitmq.conf
RUN chmod +x /custom-entrypoint.sh
RUN rabbitmq-plugins enable rabbitmq_management rabbitmq_prometheus

ENTRYPOINT ["/custom-entrypoint.sh"]
