FROM prom/node-exporter@sha256:863b62ff9f392b6f472e22b4b670ad1cabb66b3042502ebd4b2cd192733e1bce

USER root
COPY web_config.yml /etc/prometheus/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chmod 440 /etc/prometheus/*.yml
RUN chmod +x /custom-entrypoint.sh

ENTRYPOINT ["/custom-entrypoint.sh"]
