FROM prom/node-exporter:latest

USER root
COPY web_config.yml /etc/prometheus/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chmod 440 /etc/prometheus/*.yml
RUN chmod +x /custom-entrypoint.sh

ENTRYPOINT ["/custom-entrypoint.sh"]
