FROM mongodb/mongodb-community-server@sha256:78cb3e9a9c6b1be288e1e79f95008cbe82008637c002df587447c3ef2ff1d682

USER root
RUN userdel mongodb
RUN groupdel mongodb
RUN groupadd -g 3002 mongodb
RUN useradd -u 3002 -g 3002 -s /bin/sh -d /data/db mongodb
RUN mkdir /etc/mongo
COPY init.js /docker-entrypoint-initdb.d/init.js
COPY docker-entrypoint.sh /custom-entrypoint.sh
COPY mongod.conf /etc/mongod.conf
RUN chown -R mongodb:mongodb /docker-entrypoint-initdb.d/init.js /custom-entrypoint.sh /etc/mongod.conf /etc/mongo
RUN chmod +x /custom-entrypoint.sh /docker-entrypoint-initdb.d/init.js /usr/local/bin/docker-entrypoint.py
ENTRYPOINT ["/custom-entrypoint.sh"]
