apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: https://proxy:8080
    basicAuth: false
    withCredentials: false
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: false
      tlsAuthWithCACert: true
      tlsAuth: true
    secureJsonData:
      tlsCACert: |
        CA_CERT
      tlsClientCert: |
        CLIENT_CERT
      tlsClientKey: |
        CLIENT_KEY
