FROM grafana/grafana:latest

USER root
RUN deluser grafana
RUN adduser --uid 3000 --disabled-password --home /usr/share/grafana grafana
COPY grafana.ini /etc/grafana/grafana.ini
COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
