FROM grafana/grafana:latest

USER root
RUN deluser grafana
RUN adduser --uid 3000 --disabled-password --home /usr/share/grafana grafana
COPY grafana.ini /etc/grafana/
COPY docker-entrypoint.sh /custom-entrypoint.sh
COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
RUN chmod +x /custom-entrypoint.sh
ENTRYPOINT ["/custom-entrypoint.sh"]
