- name: Enable and start Firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Open Swarm TCP management port (2377)
  ansible.posix.firewalld:
    port: 2377/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Open Swarm communication ports (7946 tcp/udp)
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 7946/tcp
    - 7946/udp

- name: Open overlay network port (4789/udp)
  ansible.posix.firewalld:
    port: 4789/udp
    permanent: true
    state: enabled
    immediate: true
