- name: Initialize Docker Swarm
  ansible.builtin.command: "docker swarm init --advertise-addr {{ advertise_addr }}"
  changed_when: true

- name: Create Metrics Network
  ansible.builtin.command: "docker network create dock-schedule-proxy --driver overlay --attachable"
  changed_when: true

- name: Create Broker Network
  ansible.builtin.command: "docker network create dock-schedule-broker --driver overlay --attachable"
  changed_when: true

- name: Create Job DB Network
  ansible.builtin.command: "docker network create dock-schedule-job-db --driver overlay --attachable"
  changed_when: true

- name: Create Broker User Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "dsu-{{ 99999 | random }}" | docker secret create broker_user -
  changed_when: true

- name: Create Broker Password Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lookup('password', '/dev/null', length=20, chars='ascii_letters') }}" | docker secret create broker_passwd -
  changed_when: true

- name: Create Broker Vhost Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "dsv-{{ 99999 | random }}" | docker secret create broker_vhost -
  changed_when: true

- name: Create Mongo User Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "dsu-{{ 99999 | random }}" | docker secret create mongo_user -
  changed_when: true

- name: Create Mongo Password Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "{{ lookup('password', '/dev/null', length=20, chars='ascii_letters') }}" | docker secret create mongo_passwd -
  changed_when: true

- name: Create Mongo DB Secret
  ansible.builtin.shell: |
    set -o pipefail
    echo "dsdb-{{ 99999 | random }}" | docker secret create mongo_db -
  changed_when: true
