- name: Initialize Docker Swarm
  shell: |
    docker swarm init --advertise-addr {{ advertise_addr }}
  args:
    creates: /var/lib/docker/swarm

- name: Get join-token
  ansible.builtin.shell: docker swarm join-token -q worker
  register: worker_token

- name: Save join token to tmp file
  delegate_to: localhost
  run_once: true
  copy:
    content: "{{ worker_token.stdout }}"
    dest: /tmp/.swarm_worker_token


# Create steps to create network and secrets
