- name: Drain node of services
  delegate_to: localhost
  ansible.builtin.command: "docker node update --availability drain {{ inventory_hostname }}"
  changed_when: true

- name: Wait for node drain to complete
  ansible.builtin.command: docker ps --format json
  register: running_services
  retries: 60
  delay: 5
  until: running_services.stdout == ""
  changed_when: true
