- name: Install NFS (RedHat)
  ansible.builtin.package:
    name:
      - nfs-utils
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install NFS (Debian)
  ansible.builtin.package:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
  when: ansible_facts['os_family'] == 'Debian'
