- name: Create swarm share directory
  ansible.builtin.file:
    path: /mnt/swarm-share
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Mount swarm NFS share
  ansible.posix.mount:
    path: /mnt/swarm-share
    src: "{{ nfs_server }}:/mnt/swarm-share"
    fstype: nfs
    opts: defaults
    state: mounted
