- name: Broker Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_broker
  delegate_to: localhost
  changed_when: true

- name: Grafana Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_grafana
  delegate_to: localhost
  changed_when: true

- name: MongoDB Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_mongodb
  delegate_to: localhost
  changed_when: true

- name: MongoDB-Scraper Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_node_scraper
  delegate_to: localhost
  changed_when: true

- name: Proxy Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_proxy
  delegate_to: localhost
  changed_when: true

- name: Proxy-Scraper Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_proxy_scraper
  delegate_to: localhost
  changed_when: true

- name: Worker Service Force Update
  ansible.builtin.command: docker service update --force dock-schedule_worker
  delegate_to: localhost
  changed_when: true
