- name: Close Swarm TCP management port (2377)
  ansible.posix.firewalld:
    zone: public
    port: 2377/tcp
    permanent: true
    state: disabled
    immediate: true

- name: Close Swarm communication ports (7946 tcp/udp)
  ansible.posix.firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: true
  loop:
    - 7946/tcp
    - 7946/udp

- name: Close overlay network port (4789/udp)
  ansible.posix.firewalld:
    zone: public
    port: 4789/udp
    permanent: true
    state: disabled
    immediate: true

- name: Close NFS port (2049/tcp)
  ansible.posix.firewalld:
    zone: public
    port: 2049/tcp
    permanent: true
    state: disabled
    immediate: true

- name: Close HTTP Port (80/tcp)
  ansible.posix.firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: disabled
    immediate: true

- name: Close HTTPS Port (443/tcp)
  ansible.posix.firewalld:
    zone: public
    port: 443/tcp
    permanent: true
    state: disabled
    immediate: true

- name: Close Prometheus Port (8080/tcp)
  ansible.posix.firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: disabled
    immediate: true
