FROM prom/node-exporter:latest

USER root
COPY web_config.yml /etc/prometheus/
COPY scraper.* /etc/prometheus/
COPY dock-schedule-ca.crt /etc/prometheus/
RUN chmod 440 /etc/prometheus/*.yml /etc/prometheus/scraper.crt /etc/prometheus/scraper.key /etc/prometheus/dock-schedule-ca.crt
