FROM bitnami/nginx-exporter:latest

USER root
COPY docker-entrypoint.sh /custom-entrypoint.sh
COPY web_config.yml /opt/bitnami/
RUN chmod +x /custom-entrypoint.sh
ENTRYPOINT ["/custom-entrypoint.sh"]
