FROM mongodb/mongodb-community-server:7.0.3-ubuntu2204

USER root
COPY init.js /docker-entrypoint-initdb.d/init.js
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chown mongodb:mongodb /docker-entrypoint-initdb.d/init.js /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh /docker-entrypoint-initdb.d/init.js /usr/local/bin/docker-entrypoint.py
ENTRYPOINT ["/custom-entrypoint.sh"]
