{
 "title": "Broker",
 "description": "Job Broker Metrics",
 "tags": [
  "jobs",
  "broker",
  "scheduler",
  "workers"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(rabbitmq_identity_info, namespace)"
    }
   },
   { "name": "rabbitmq_cluster", "label": "RabbitMQ Cluster", "query": "rabbit@dschedule" }
  ]
 },
 "panels": [
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler Queue",
   "type": "graph",
   "description": "The number of jobs that are pending to be sent to workers. Each worker has their own queue. This will start filling up when the worker queues are full and a job cannot be sent to a worker. When this number is increasing it means to deploy more workers in the cluster.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)",
     "legendFormat": "Queued Jobs"
    }
   ]
  },
  {
   "title": "Returned Jobs / s",
   "type": "graph",
   "description": "The rate of jobs that are un-routable and have been returned to sender to retry. This usually happens when the scheduler job queue has become too full.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_unroutable_returned_total[60s]))",
     "legendFormat": "Returned Jobs"
    }
   ]
  },
  {
   "title": "Scheduled Jobs / s",
   "type": "graph",
   "description": "The rate of jobs being sent to workers in the cluster.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(rabbitmq_queue_messages_published_total[60s]))",
     "legendFormat": "Scheduled Jobs"
    }
   ]
  },
  {
   "title": "Scheduler Connections",
   "type": "graph",
   "description": "The number of scheduler connections. The scheduler uses threads to schedule jobs in parallel and each thread has its own connection. Each scheduler should have three connections and there should only be one scheduler in the cluster.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_global_publishers)",
     "legendFormat": "Schedulers"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Worker Queue",
   "type": "graph",
   "description": "Number of jobs sent to workers and are either running or waiting to run by a worker. Each worker has three threads and each thread can queue three jobs so each worker can be scheduled three active jobs and 6 inactive jobs for a total of 9 jobs.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked)",
     "legendFormat": "Queued Jobs"
    }
   ]
  },
  {
   "title": "Jobs Rescheduled / s",
   "type": "graph",
   "description": "The rate of jobs resent to workers. Usually happens when workers hold onto a job for too long or when a worker is decommissioned and its pending jobs were rescheduled to other workers in the cluster.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]))",
     "legendFormat": "Rescheduled Jobs"
    }
   ]
  },
  {
   "title": "Jobs Received / s",
   "type": "graph",
   "description": "The rate of jobs received by workers. You should try to match this to the number of scheduled jobs per second as best as possible. A quantity mismatch will cause the scheduler queue to start filling up and jobs will not run at the expected time.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]))",
     "legendFormat": "Received Jobs"
    }
   ]
  },
  {
   "title": "Worker Connections",
   "type": "graph",
   "description": "The number of worker connections. The workers use threads to run jobs in parallel and each thread has its own connection. Each worker should have three connections.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "sum(rabbitmq_consumers)", "legendFormat": "Workers" }
   ]
  },
  {
   "title": "Jobs Completed / s",
   "type": "graph",
   "description": "The rate of completed jobs.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_acknowledged_total[60s]))",
     "legendFormat": "Completed Jobs"
    }
   ]
  }
 ]
}