{
 "title": "Hosts",
 "description": "Swarm Node Metrics",
 "tags": [
  "swarm",
  "nodes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "Node-Scrape" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "System Load (1M)",
   "type": "gauge",
   "description": "Average system load for the last minute",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load (5M)",
   "type": "gauge",
   "description": "Average system load for the last 5 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load5{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load (15M)",
   "type": "gauge",
   "description": "Average system load for the last 15 minutes",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load15{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Used memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Swarm Share",
   "type": "gauge",
   "description": "Used Swarm share",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/opt/dock-schedule\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/opt/dock-schedule\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"}) or 100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "description": "OS Name",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\", job=\"$job\"} - node_boot_time_seconds{instance=\"$node\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "description": "Running Processes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$node\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Blocked Processes",
   "type": "stat",
   "description": "Blocked Processes",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_blocked{instance=\"$node\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Swarm Share Total",
   "type": "stat",
   "description": "Total Swarm share",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (node_filesystem_size_bytes{mountpoint=\"/opt/dock-schedule\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"} or node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"rootfs|tmpfs\", instance=\"$node\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "NTP Drift (PPM)",
   "type": "stat",
   "description": "Clock drift adjustment in parts per million (PPM)",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_timex_frequency_adjustment_ratio{instance=\"$node\", job=\"$job\"} - 1) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "timeseries",
     "description": "Busy state of the system CPUs together",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "IOwait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "IRQs"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Other"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[60s])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - rate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode=\"idle\"}[30s])) * 100",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Processes Status",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Running"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "System memory usage",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Cache/Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Free"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Operations",
     "type": "timeseries",
     "description": "Write operations for found disks",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Read Operations",
     "type": "timeseries",
     "description": "Read operations for found disks",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "timeseries",
     "description": "Data written to found disks",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Data Read",
     "type": "timeseries",
     "description": "Data read from found disks",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Average Write Wait Time",
     "type": "timeseries",
     "description": "The average write time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / clamp_min(irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]), 1)",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Average Read Wait Time",
     "type": "timeseries",
     "description": "The average read time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / clamp_min(irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]), 1)",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "description": "Percent of disk busy time",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "The average queue length of the requests that were issued to the device",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "description": "Disk space used of all mounted filesystems",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~\"rootfs|none|tmpfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~\"rootfs|none|tmpfs\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmitted Data",
     "type": "timeseries",
     "description": "Transmitted network traffic for found interfaces",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Received Data",
     "type": "timeseries",
     "description": "Received network traffic for found interfaces",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Softnet Packets Processed",
     "type": "timeseries",
     "description": "Packets processed by softnet- Kernel high speed network traffic handler",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_softnet_processed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Softnet Packets Dropped",
     "type": "timeseries",
     "description": "Packets dropped by softnet- Kernel high speed network traffic handler. Dropped packets are an indicator the kernel could not keep up with the network load.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_softnet_dropped_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Softnet Squeezed",
     "type": "timeseries",
     "description": "Squeezed packets by softnet- Kernel high speed network traffic handler. An increase of squeezed counters indicate the CPU had to interrupt processing the network packets due to time budget constraints, network packet processing is falling behind.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_softnet_times_squeezed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "timeseries",
     "description": "ARP entries for found interfaces. Mapping of IP addresses to MAC addresses.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  }
 ]
}