{
 "title": "Jobs",
 "description": "Job Metrics",
 "tags": [
  "schedule",
  "jobs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "Job-Scrape" },
   { "name": "instance", "label": "instance", "query": "scheduler" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending Jobs",
   "type": "stat",
   "description": "Total jobs sitting in the broker queue waiting to be sent to a worker. Have not been delivered to a worker yet.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_pending{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "description": "Total amount of jobs that are currently running in the cluster. Each worker can run three jobs in parallel. The total number of jobs that can run at a time is worker-qty x 3. If this number matches your current deployment then you have reached your limit of parallel jobs and it is a good time to scale up the worker quantity before a job backlog occurs.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_running{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Jobs",
   "type": "stat",
   "description": "Total amount of jobs that have been successful.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_successful_total{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "description": "Total amount of jobs that have failed.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_failed_total{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Completed Jobs",
   "type": "stat",
   "description": "Total completed jobs. Jobs get deleted every 7 days from the database.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_total{instance=\"$instance\", job=\"$job\"} - (scheduler_jobs_running{instance=\"$instance\", job=\"$job\"} + scheduler_jobs_pending{instance=\"$instance\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "description": "Total jobs run. Jobs get deleted every 7 days from the database",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_jobs_total{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Crons",
   "type": "stat",
   "description": "Total amount of job crons created",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_crons_total{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Enabled Crons",
   "type": "stat",
   "description": "Total amount of job crons enabled",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scheduler_crons_enabled_total{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Jobs",
     "type": "graph",
     "description": "Jobs waiting to be scheduled",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Jobs" }
     ],
     "targets": [
      { "expr": "scheduler_jobs_pending", "legendFormat": "Jobs" }
     ]
    },
    {
     "title": "Running Jobs",
     "type": "graph",
     "description": "Jobs currently running",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Jobs" }
     ],
     "targets": [
      { "expr": "scheduler_jobs_running", "legendFormat": "Jobs" }
     ]
    }
   ]
  },
  {
   "title": "Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job States",
     "type": "graph",
     "description": "Completed job states",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short", "label": "Jobs" }
     ],
     "targets": [
      {
       "expr": "increase(scheduler_jobs_successful_total[$__rate_interval])",
       "legendFormat": "Successful"
      },
      {
       "expr": "increase(scheduler_jobs_failed_total[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  }
 ]
}