{
 "title": "Job Database",
 "description": "Job Database Metrics",
 "tags": [
  "jobs",
  "mongo",
  "db"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster" },
   { "name": "job", "label": "job", "query": "Mongo-Scrape" },
   { "name": "instance", "label": "Instance", "query": "mongodb_scraper" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service State",
   "type": "stat",
   "description": "Current state of the MongoDB service",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Utilization",
   "type": "gauge",
   "description": "Connection utilization of active connections to allowed amount of connections.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(mongodb_ss_connections{conn_type=\"current\"}) / (sum(mongodb_ss_connections{conn_type=\"current\"}) + sum(mongodb_ss_connections{conn_type=\"available\"}))) * 100"
    }
   ]
  },
  {
   "title": "Connection Activity",
   "type": "graph",
   "description": "The number of connections to the MongoDB server. Current includes threaded or pooled connections waiting for activity and active connections are connected clients. Rejected connections are those that were refused by the server.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"active\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "mongodb_ss_connections{conn_type=\"rejected\", instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Commands / s",
   "type": "graph",
   "description": "The rate of command operations received",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mongodb_ss_opcounters{legacy_op_type=\"command\", instance=\"$instance\", job=\"$job\"}[60s]))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inserts / s",
   "type": "graph",
   "description": "The rate of insert operations received",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mongodb_ss_opcounters{legacy_op_type=\"insert\", instance=\"$instance\", job=\"$job\"}[60s]))",
     "legendFormat": "Inserts"
    }
   ]
  },
  {
   "title": "Updates / s",
   "type": "graph",
   "description": "The rate of update operations received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mongodb_ss_opcounters{legacy_op_type=\"update\", instance=\"$instance\", job=\"$job\"}[60s]))",
     "legendFormat": "Updates"
    }
   ]
  },
  {
   "title": "Deletes / s",
   "type": "graph",
   "description": "The rate of delete operations received",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters{legacy_op_type=\"delete\", instance=\"$instance\", job=\"$job\"}[60s]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Reads / s",
   "type": "graph",
   "description": "The rate of read (query) operations received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mongodb_ss_opcounters{legacy_op_type=\"query\", instance=\"$instance\", job=\"$job\"}[60s]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Write Latency",
   "type": "graph",
   "description": "Average Write Latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "(rate(mongodb_ss_opLatencies_latency{op_type=\"writes\"}[60s]) / rate(mongodb_ss_opLatencies_ops{op_type=\"writes\"}[60s])) / 1000",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Avg Read Latency",
   "type": "graph",
   "description": "Average Read Latency",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "(rate(mongodb_ss_opLatencies_latency{op_type=\"reads\"}[60s]) / rate(mongodb_ss_opLatencies_ops{op_type=\"reads\"}[60s])) / 1000",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Avg Command Latency",
   "type": "graph",
   "description": "Average Command Latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "(rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[60s]) / rate(mongodb_ss_opLatencies_ops{op_type=\"commands\"}[60s])) / 1000",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job DB Size",
   "type": "graph",
   "description": "Database Size. Total size is the sum of the collections and indexes.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "mongodb_dbstats_totalSize{instance=\"$instance\", job=\"$job\", database!~\"^(admin|local|config)$\"}",
     "legendFormat": "Total Size"
    },
    {
     "expr": "mongodb_dbstats_storageSize{instance=\"$instance\", job=\"$job\", database!~\"^(admin|local|config)$\"}",
     "legendFormat": "Collections"
    },
    {
     "expr": "mongodb_dbstats_indexSize{instance=\"$instance\", job=\"$job\", database!~\"^(admin|local|config)$\"}",
     "legendFormat": "Indexes"
    }
   ]
  }
 ]
}