{
 "title": "Proxy Service",
 "description": "Proxy Service Metrics",
 "tags": [
  "proxy",
  "nginx"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service State",
   "type": "stat",
   "description": "Current state of the proxy service",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Utilization",
   "type": "gauge",
   "description": "Active connections as a percentage of the maximum number of connections (1024).",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nginx_connections_active{instance=~\"$instance\"} / 1024) * 100"
    }
   ]
  },
  {
   "title": "Connection Drops",
   "type": "gauge",
   "description": "Connection drops",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (nginx_connections_handled{instance=~\"$instance\"} / clamp_min(nginx_connections_accepted{instance=~\"$instance\"}, 1))) * 100"
    }
   ]
  },
  {
   "title": "Reading Clients",
   "type": "gauge",
   "description": "Active connections currently reading. High values indicate slow clients, high TLS handshake overhead, or DoS attack",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nginx_connections_reading{instance=~\"$instance\"} / clamp_min(nginx_connections_active{instance=~\"$instance\"}, 1)) * 100"
    }
   ]
  },
  {
   "title": "Writing Clients",
   "type": "gauge",
   "description": "Active connections currently writing. High values indicate slow client download speeds, large payloads being sent or streaming, or latency in the backend servics.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nginx_connections_writing{instance=~\"$instance\"} / clamp_min(nginx_connections_active{instance=~\"$instance\"}, 1)) * 100"
    }
   ]
  },
  {
   "title": "Waiting Clients",
   "type": "gauge",
   "description": "Active connections currently waiting- keepalive clients",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nginx_connections_waiting{instance=~\"$instance\"} / clamp_min(nginx_connections_active{instance=~\"$instance\"}, 1)) * 100"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m]) - irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Connection Activity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "total requests"
    }
   ]
  }
 ]
}