{
 "title": "Swarm",
 "description": "Swarm Cluster Overview",
 "tags": [
  "swarm",
  "cluster",
  "nodes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "Node-Scrape" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Average cluster CPU busy",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval]))/ sum(rate(node_cpu_seconds_total{}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "Load (1M)",
   "type": "gauge",
   "description": "Average cluster load for the last minute",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load1) / count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu, instance)) * 100"
    }
   ]
  },
  {
   "title": "Load (5M)",
   "type": "gauge",
   "description": "Average cluster load for the last five minute",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load5) / count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu, instance)) * 100"
    }
   ]
  },
  {
   "title": "Load (15M)",
   "type": "gauge",
   "description": "Average cluster load for the last fifteen minute",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_load15) / count(count(node_cpu_seconds_total{mode=\"idle\"}) by (cpu, instance)) * 100"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "Cluster used memory percentage",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Cluster used root filesystem percentage as a whole",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}) * 100) / sum(node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}))"
    }
   ]
  },
  {
   "title": "Swarm Share",
   "type": "gauge",
   "description": "Used Swarm share",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by (instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/opt/dock-schedule\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/opt/dock-schedule\"}) or 100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) by (id)",
     "legendFormat": "TX"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval])) by (id)",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "description": "Cluster running processes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_procs_running)" }
   ]
  },
  {
   "title": "Blocked Processes",
   "type": "stat",
   "description": "Processes blocked within the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(node_procs_blocked)" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total cluster memory",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Root FS Total",
   "type": "stat",
   "description": "Cluster total root filesystem size as a whole",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Swarm Share Total",
   "type": "stat",
   "description": "Total Swarm share",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by (instance) (node_filesystem_size_bytes{mountpoint=\"/opt/dock-schedule\"} unless node_filesystem_size_bytes{mountpoint=\"/\"}))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total number of containers running on the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{container_label_com_docker_stack_namespace=\"dock-schedule\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Swarm Nodes",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{mode=\"user\"}) by (cpu, instance)) by (instance)"
      },
      { "expr": "node_memory_MemTotal_bytes" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "timeseries",
     "description": "Cluster CPU Busy state",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Container CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"Container-Scrape\", container_label_com_docker_stack_namespace=\"dock-schedule\"}[$__rate_interval])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Cluster CPU Usage",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100",
       "legendFormat": "{{instance}} CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "Processes Status",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(node_procs_blocked)", "legendFormat": "Blocked" },
      { "expr": "sum(node_procs_running)", "legendFormat": "Running" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Cluster memory usage. This includes reclaimable cache and buffers usage",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{container_label_com_docker_stack_namespace=\"dock-schedule\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Operations",
     "type": "timeseries",
     "description": "Cluster write operations",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_writes_completed_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Read Operations",
     "type": "timeseries",
     "description": "Cluster read operations",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "timeseries",
     "description": "Cluster written data",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "timeseries",
     "description": "Cluster read data",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Average Write Wait Time",
     "type": "timeseries",
     "description": "Cluster average write wait time. Write latency",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total[$__rate_interval]) / clamp_min(rate(node_disk_writes_completed_total[$__rate_interval]), 1)",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Average Read Wait Time",
     "type": "timeseries",
     "description": "Cluster average read wait time. Read latency",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total[$__rate_interval]) / clamp_min(rate(node_disk_reads_completed_total[$__rate_interval]), 1)",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "description": "Cluster disk percent busy time",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "cluster average queue length of the requests",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total[$__rate_interval])",
       "legendFormat": "{{instance}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmitted Data",
     "type": "timeseries",
     "description": "Cluster transmitted network traffic",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Data",
     "type": "timeseries",
     "description": "Cluster received network traffic",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Transmitted Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (rate(container_network_transmit_packets_total{id=\"/\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (rate(container_network_receive_packets_total{id=\"/\"}[$__rate_interval]))",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(rate(container_network_receive_packets_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Dropped Transmit Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (container_network_transmit_packets_dropped_total{id=\"/\"})",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(container_network_transmit_packets_dropped_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Dropped Receive Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance, interface) (container_network_receive_packets_dropped_total{id=\"/\"})",
       "legendFormat": "{{instance}} {{interface}}"
      },
      {
       "expr": "sum(container_network_receive_packets_dropped_total{container_label_com_docker_stack_namespace=\"dock-schedule\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Softnet Packets Processed",
     "type": "timeseries",
     "description": "Cluster packets processed by softnet",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_softnet_processed_total[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Softnet Packets Dropped",
     "type": "timeseries",
     "description": "Cluster packets dropped by softnet. Dropped packets are an indicator the kernel could not keep up with the network load.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_softnet_dropped_total[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Softnet Squeezed",
     "type": "timeseries",
     "description": "Cluster squeezed packets by softnet. An increase of squeezed counters indicate the CPU had to interrupt processing the network packets due to time budget constraints, network packet processing is falling behind.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_softnet_times_squeezed_total[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "timeseries",
     "description": "Cluster ARP entries. Mapping of IP addresses to MAC addresses.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_arp_entries) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}