FROM prom/prometheus:latest

USER root
COPY *.yml /etc/prometheus/
COPY prometheus.* /etc/prometheus/
COPY dock-schedule-ca.crt /etc/prometheus/
RUN chmod 440 /etc/prometheus/*.yml /etc/prometheus/prometheus.crt /etc/prometheus/prometheus.key /etc/prometheus/dock-schedule-ca.crt
