FROM prom/prometheus:latest

USER root
COPY *.yml /etc/prometheus/
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chmod 440 /etc/prometheus/*.yml
RUN chmod +x /custom-entrypoint.sh

ENTRYPOINT ["/custom-entrypoint.sh" ]
