global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Node-Scrape
    scheme: https
    params:
      ip: [$1]
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/host.crt
      key_file: /etc/prometheus/host.key
      insecure_skip_verify: false
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 9100
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: node-stats
        action: keep
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: dock-schedule-proxy
        action: keep
      - source_labels: [__address__]
        regex: (.+):\d+
        target_label: __param_ip
      - source_labels: [__address__]
        replacement: proxy:8081
        target_label: __address__
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: Container-Scrape
    scheme: https
    params:
      ip: [$1]
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/host.crt
      key_file: /etc/prometheus/host.key
      insecure_skip_verify: false
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 8070
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: container-stats
        action: keep
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: dock-schedule-proxy
        action: keep
      - source_labels: [__address__]
        regex: (.+):\d+
        target_label: __param_ip
      - source_labels: [__address__]
        replacement: proxy:8085
        target_label: __address__
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: Broker-Scrape
    scheme: https
    params:
      host: [broker]
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/host.crt
      key_file: /etc/prometheus/host.key
      insecure_skip_verify: false
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 15691
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: broker-stats
        action: keep
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: dock-schedule-proxy
        action: keep
      - source_labels: [__address__]
        replacement: proxy:8082
        target_label: __address__
      - source_labels: [instance]
        replacement: broker
        target_label: instance

  - job_name: Mongo-Scrape
    scheme: https
    params:
      host: [mongodb_scraper]
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/host.crt
      key_file: /etc/prometheus/host.key
      insecure_skip_verify: false
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 9216
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: mongo-stats
        action: keep
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: dock-schedule-proxy
        action: keep
      - source_labels: [__address__]
        replacement: proxy:8083
        target_label: __address__
      - source_labels: [instance]
        replacement: mongodb_scraper
        target_label: instance

  - job_name: Proxy-Scrape
    scheme: https
    params:
      host: [proxy_scraper]
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/host.crt
      key_file: /etc/prometheus/host.key
      insecure_skip_verify: false
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        port: 9113
    relabel_configs:
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: proxy-stats
        action: keep
      - source_labels: [__meta_dockerswarm_task_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_network_name]
        regex: dock-schedule-proxy
        action: keep
      - source_labels: [__address__]
        replacement: proxy:8084
        target_label: __address__
      - source_labels: [instance]
        replacement: proxy
        target_label: instance
