---
- name: Add Node to Swarm
  hosts: all
  gather_facts: false
  become: true
  vars:
    nfs_server: ''
    manager_ip: ""
    token: ""
  tasks:
    - name: Create Grafana User
      ansible.builtin.import_tasks: tasks/create_grafana_user.yml

    - name: Create RabbitMQ User
      ansible.builtin.import_tasks: tasks/create_rabbitmq_user.yml

    - name: Create MongoDB User
      ansible.builtin.import_tasks: tasks/create_mongodb_user.yml

    - name: Mount Swarm NFS Share
      ansible.builtin.import_tasks: tasks/mount_swarm_share.yml

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/install_docker.yml

    - name: Add Swarm Firewall Rules
      ansible.builtin.import_tasks: tasks/add_swarm_firewall_rules.yml

    - name: Sync Dock-Schedule Files
      ansible.builtin.import_tasks: tasks/sync_dock_schedule_services.yml

    - name: Build Docker Swarm Services
      ansible.builtin.import_tasks: tasks/build_containers.yml

    - name: Join Swarm
      ansible.builtin.import_tasks: tasks/join_swarm.yml
